build:
  version: "2.0"

cards:
  name: "Welcome to Unicobank QA Cards APIs"
  contactDetails:
    name: "Jannie jos - QA Lead"
    email: "jos.j12@bank.com"
  onCallSupport:
    - (91) 4332-091234
    - (91) 4569-234102